// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: replacement.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_replacement_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_replacement_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_replacement_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_replacement_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_replacement_2eproto;
namespace fira_message {
namespace sim_to_ref {
class BallReplacement;
class BallReplacementDefaultTypeInternal;
extern BallReplacementDefaultTypeInternal _BallReplacement_default_instance_;
class Replacement;
class ReplacementDefaultTypeInternal;
extern ReplacementDefaultTypeInternal _Replacement_default_instance_;
class RobotReplacement;
class RobotReplacementDefaultTypeInternal;
extern RobotReplacementDefaultTypeInternal _RobotReplacement_default_instance_;
}  // namespace sim_to_ref
}  // namespace fira_message
PROTOBUF_NAMESPACE_OPEN
template<> ::fira_message::sim_to_ref::BallReplacement* Arena::CreateMaybeMessage<::fira_message::sim_to_ref::BallReplacement>(Arena*);
template<> ::fira_message::sim_to_ref::Replacement* Arena::CreateMaybeMessage<::fira_message::sim_to_ref::Replacement>(Arena*);
template<> ::fira_message::sim_to_ref::RobotReplacement* Arena::CreateMaybeMessage<::fira_message::sim_to_ref::RobotReplacement>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace fira_message {
namespace sim_to_ref {

// ===================================================================

class RobotReplacement PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.RobotReplacement) */ {
 public:
  inline RobotReplacement() : RobotReplacement(nullptr) {};
  virtual ~RobotReplacement();

  RobotReplacement(const RobotReplacement& from);
  RobotReplacement(RobotReplacement&& from) noexcept
    : RobotReplacement() {
    *this = ::std::move(from);
  }

  inline RobotReplacement& operator=(const RobotReplacement& from) {
    CopyFrom(from);
    return *this;
  }
  inline RobotReplacement& operator=(RobotReplacement&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RobotReplacement& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RobotReplacement* internal_default_instance() {
    return reinterpret_cast<const RobotReplacement*>(
               &_RobotReplacement_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RobotReplacement& a, RobotReplacement& b) {
    a.Swap(&b);
  }
  inline void Swap(RobotReplacement* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RobotReplacement* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RobotReplacement* New() const final {
    return CreateMaybeMessage<RobotReplacement>(nullptr);
  }

  RobotReplacement* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RobotReplacement>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RobotReplacement& from);
  void MergeFrom(const RobotReplacement& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RobotReplacement* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fira_message.sim_to_ref.RobotReplacement";
  }
  protected:
  explicit RobotReplacement(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_replacement_2eproto);
    return ::descriptor_table_replacement_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kYellowteamFieldNumber = 5,
    kTurnonFieldNumber = 6,
  };
  // .fira_message.Robot position = 1;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::fira_message::Robot& position() const;
  ::fira_message::Robot* release_position();
  ::fira_message::Robot* mutable_position();
  void set_allocated_position(::fira_message::Robot* position);
  private:
  const ::fira_message::Robot& _internal_position() const;
  ::fira_message::Robot* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::fira_message::Robot* position);
  ::fira_message::Robot* unsafe_arena_release_position();

  // bool yellowteam = 5;
  void clear_yellowteam();
  bool yellowteam() const;
  void set_yellowteam(bool value);
  private:
  bool _internal_yellowteam() const;
  void _internal_set_yellowteam(bool value);
  public:

  // bool turnon = 6;
  void clear_turnon();
  bool turnon() const;
  void set_turnon(bool value);
  private:
  bool _internal_turnon() const;
  void _internal_set_turnon(bool value);
  public:

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.RobotReplacement)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::fira_message::Robot* position_;
  bool yellowteam_;
  bool turnon_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_replacement_2eproto;
};
// -------------------------------------------------------------------

class BallReplacement PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.BallReplacement) */ {
 public:
  inline BallReplacement() : BallReplacement(nullptr) {};
  virtual ~BallReplacement();

  BallReplacement(const BallReplacement& from);
  BallReplacement(BallReplacement&& from) noexcept
    : BallReplacement() {
    *this = ::std::move(from);
  }

  inline BallReplacement& operator=(const BallReplacement& from) {
    CopyFrom(from);
    return *this;
  }
  inline BallReplacement& operator=(BallReplacement&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BallReplacement& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BallReplacement* internal_default_instance() {
    return reinterpret_cast<const BallReplacement*>(
               &_BallReplacement_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BallReplacement& a, BallReplacement& b) {
    a.Swap(&b);
  }
  inline void Swap(BallReplacement* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BallReplacement* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BallReplacement* New() const final {
    return CreateMaybeMessage<BallReplacement>(nullptr);
  }

  BallReplacement* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BallReplacement>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BallReplacement& from);
  void MergeFrom(const BallReplacement& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BallReplacement* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fira_message.sim_to_ref.BallReplacement";
  }
  protected:
  explicit BallReplacement(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_replacement_2eproto);
    return ::descriptor_table_replacement_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kVxFieldNumber = 3,
    kVyFieldNumber = 4,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double vx = 3;
  void clear_vx();
  double vx() const;
  void set_vx(double value);
  private:
  double _internal_vx() const;
  void _internal_set_vx(double value);
  public:

  // double vy = 4;
  void clear_vy();
  double vy() const;
  void set_vy(double value);
  private:
  double _internal_vy() const;
  void _internal_set_vy(double value);
  public:

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.BallReplacement)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double x_;
  double y_;
  double vx_;
  double vy_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_replacement_2eproto;
};
// -------------------------------------------------------------------

class Replacement PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fira_message.sim_to_ref.Replacement) */ {
 public:
  inline Replacement() : Replacement(nullptr) {};
  virtual ~Replacement();

  Replacement(const Replacement& from);
  Replacement(Replacement&& from) noexcept
    : Replacement() {
    *this = ::std::move(from);
  }

  inline Replacement& operator=(const Replacement& from) {
    CopyFrom(from);
    return *this;
  }
  inline Replacement& operator=(Replacement&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Replacement& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Replacement* internal_default_instance() {
    return reinterpret_cast<const Replacement*>(
               &_Replacement_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Replacement& a, Replacement& b) {
    a.Swap(&b);
  }
  inline void Swap(Replacement* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Replacement* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Replacement* New() const final {
    return CreateMaybeMessage<Replacement>(nullptr);
  }

  Replacement* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Replacement>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Replacement& from);
  void MergeFrom(const Replacement& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Replacement* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fira_message.sim_to_ref.Replacement";
  }
  protected:
  explicit Replacement(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_replacement_2eproto);
    return ::descriptor_table_replacement_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRobotsFieldNumber = 2,
    kBallFieldNumber = 1,
  };
  // repeated .fira_message.sim_to_ref.RobotReplacement robots = 2;
  int robots_size() const;
  private:
  int _internal_robots_size() const;
  public:
  void clear_robots();
  ::fira_message::sim_to_ref::RobotReplacement* mutable_robots(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement >*
      mutable_robots();
  private:
  const ::fira_message::sim_to_ref::RobotReplacement& _internal_robots(int index) const;
  ::fira_message::sim_to_ref::RobotReplacement* _internal_add_robots();
  public:
  const ::fira_message::sim_to_ref::RobotReplacement& robots(int index) const;
  ::fira_message::sim_to_ref::RobotReplacement* add_robots();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement >&
      robots() const;

  // .fira_message.sim_to_ref.BallReplacement ball = 1;
  bool has_ball() const;
  private:
  bool _internal_has_ball() const;
  public:
  void clear_ball();
  const ::fira_message::sim_to_ref::BallReplacement& ball() const;
  ::fira_message::sim_to_ref::BallReplacement* release_ball();
  ::fira_message::sim_to_ref::BallReplacement* mutable_ball();
  void set_allocated_ball(::fira_message::sim_to_ref::BallReplacement* ball);
  private:
  const ::fira_message::sim_to_ref::BallReplacement& _internal_ball() const;
  ::fira_message::sim_to_ref::BallReplacement* _internal_mutable_ball();
  public:
  void unsafe_arena_set_allocated_ball(
      ::fira_message::sim_to_ref::BallReplacement* ball);
  ::fira_message::sim_to_ref::BallReplacement* unsafe_arena_release_ball();

  // @@protoc_insertion_point(class_scope:fira_message.sim_to_ref.Replacement)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement > robots_;
  ::fira_message::sim_to_ref::BallReplacement* ball_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_replacement_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RobotReplacement

// .fira_message.Robot position = 1;
inline bool RobotReplacement::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool RobotReplacement::has_position() const {
  return _internal_has_position();
}
inline const ::fira_message::Robot& RobotReplacement::_internal_position() const {
  const ::fira_message::Robot* p = position_;
  return p != nullptr ? *p : *reinterpret_cast<const ::fira_message::Robot*>(
      &::fira_message::_Robot_default_instance_);
}
inline const ::fira_message::Robot& RobotReplacement::position() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.RobotReplacement.position)
  return _internal_position();
}
inline void RobotReplacement::unsafe_arena_set_allocated_position(
    ::fira_message::Robot* position) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fira_message.sim_to_ref.RobotReplacement.position)
}
inline ::fira_message::Robot* RobotReplacement::release_position() {
  
  ::fira_message::Robot* temp = position_;
  position_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::fira_message::Robot* RobotReplacement::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:fira_message.sim_to_ref.RobotReplacement.position)
  
  ::fira_message::Robot* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::fira_message::Robot* RobotReplacement::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::fira_message::Robot>(GetArena());
    position_ = p;
  }
  return position_;
}
inline ::fira_message::Robot* RobotReplacement::mutable_position() {
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.RobotReplacement.position)
  return _internal_mutable_position();
}
inline void RobotReplacement::set_allocated_position(::fira_message::Robot* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position)->GetArena();
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:fira_message.sim_to_ref.RobotReplacement.position)
}

// bool yellowteam = 5;
inline void RobotReplacement::clear_yellowteam() {
  yellowteam_ = false;
}
inline bool RobotReplacement::_internal_yellowteam() const {
  return yellowteam_;
}
inline bool RobotReplacement::yellowteam() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.RobotReplacement.yellowteam)
  return _internal_yellowteam();
}
inline void RobotReplacement::_internal_set_yellowteam(bool value) {
  
  yellowteam_ = value;
}
inline void RobotReplacement::set_yellowteam(bool value) {
  _internal_set_yellowteam(value);
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.RobotReplacement.yellowteam)
}

// bool turnon = 6;
inline void RobotReplacement::clear_turnon() {
  turnon_ = false;
}
inline bool RobotReplacement::_internal_turnon() const {
  return turnon_;
}
inline bool RobotReplacement::turnon() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.RobotReplacement.turnon)
  return _internal_turnon();
}
inline void RobotReplacement::_internal_set_turnon(bool value) {
  
  turnon_ = value;
}
inline void RobotReplacement::set_turnon(bool value) {
  _internal_set_turnon(value);
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.RobotReplacement.turnon)
}

// -------------------------------------------------------------------

// BallReplacement

// double x = 1;
inline void BallReplacement::clear_x() {
  x_ = 0;
}
inline double BallReplacement::_internal_x() const {
  return x_;
}
inline double BallReplacement::x() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.BallReplacement.x)
  return _internal_x();
}
inline void BallReplacement::_internal_set_x(double value) {
  
  x_ = value;
}
inline void BallReplacement::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.BallReplacement.x)
}

// double y = 2;
inline void BallReplacement::clear_y() {
  y_ = 0;
}
inline double BallReplacement::_internal_y() const {
  return y_;
}
inline double BallReplacement::y() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.BallReplacement.y)
  return _internal_y();
}
inline void BallReplacement::_internal_set_y(double value) {
  
  y_ = value;
}
inline void BallReplacement::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.BallReplacement.y)
}

// double vx = 3;
inline void BallReplacement::clear_vx() {
  vx_ = 0;
}
inline double BallReplacement::_internal_vx() const {
  return vx_;
}
inline double BallReplacement::vx() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.BallReplacement.vx)
  return _internal_vx();
}
inline void BallReplacement::_internal_set_vx(double value) {
  
  vx_ = value;
}
inline void BallReplacement::set_vx(double value) {
  _internal_set_vx(value);
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.BallReplacement.vx)
}

// double vy = 4;
inline void BallReplacement::clear_vy() {
  vy_ = 0;
}
inline double BallReplacement::_internal_vy() const {
  return vy_;
}
inline double BallReplacement::vy() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.BallReplacement.vy)
  return _internal_vy();
}
inline void BallReplacement::_internal_set_vy(double value) {
  
  vy_ = value;
}
inline void BallReplacement::set_vy(double value) {
  _internal_set_vy(value);
  // @@protoc_insertion_point(field_set:fira_message.sim_to_ref.BallReplacement.vy)
}

// -------------------------------------------------------------------

// Replacement

// .fira_message.sim_to_ref.BallReplacement ball = 1;
inline bool Replacement::_internal_has_ball() const {
  return this != internal_default_instance() && ball_ != nullptr;
}
inline bool Replacement::has_ball() const {
  return _internal_has_ball();
}
inline void Replacement::clear_ball() {
  if (GetArena() == nullptr && ball_ != nullptr) {
    delete ball_;
  }
  ball_ = nullptr;
}
inline const ::fira_message::sim_to_ref::BallReplacement& Replacement::_internal_ball() const {
  const ::fira_message::sim_to_ref::BallReplacement* p = ball_;
  return p != nullptr ? *p : *reinterpret_cast<const ::fira_message::sim_to_ref::BallReplacement*>(
      &::fira_message::sim_to_ref::_BallReplacement_default_instance_);
}
inline const ::fira_message::sim_to_ref::BallReplacement& Replacement::ball() const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Replacement.ball)
  return _internal_ball();
}
inline void Replacement::unsafe_arena_set_allocated_ball(
    ::fira_message::sim_to_ref::BallReplacement* ball) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(ball_);
  }
  ball_ = ball;
  if (ball) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fira_message.sim_to_ref.Replacement.ball)
}
inline ::fira_message::sim_to_ref::BallReplacement* Replacement::release_ball() {
  
  ::fira_message::sim_to_ref::BallReplacement* temp = ball_;
  ball_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::fira_message::sim_to_ref::BallReplacement* Replacement::unsafe_arena_release_ball() {
  // @@protoc_insertion_point(field_release:fira_message.sim_to_ref.Replacement.ball)
  
  ::fira_message::sim_to_ref::BallReplacement* temp = ball_;
  ball_ = nullptr;
  return temp;
}
inline ::fira_message::sim_to_ref::BallReplacement* Replacement::_internal_mutable_ball() {
  
  if (ball_ == nullptr) {
    auto* p = CreateMaybeMessage<::fira_message::sim_to_ref::BallReplacement>(GetArena());
    ball_ = p;
  }
  return ball_;
}
inline ::fira_message::sim_to_ref::BallReplacement* Replacement::mutable_ball() {
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Replacement.ball)
  return _internal_mutable_ball();
}
inline void Replacement::set_allocated_ball(::fira_message::sim_to_ref::BallReplacement* ball) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete ball_;
  }
  if (ball) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(ball);
    if (message_arena != submessage_arena) {
      ball = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ball, submessage_arena);
    }
    
  } else {
    
  }
  ball_ = ball;
  // @@protoc_insertion_point(field_set_allocated:fira_message.sim_to_ref.Replacement.ball)
}

// repeated .fira_message.sim_to_ref.RobotReplacement robots = 2;
inline int Replacement::_internal_robots_size() const {
  return robots_.size();
}
inline int Replacement::robots_size() const {
  return _internal_robots_size();
}
inline void Replacement::clear_robots() {
  robots_.Clear();
}
inline ::fira_message::sim_to_ref::RobotReplacement* Replacement::mutable_robots(int index) {
  // @@protoc_insertion_point(field_mutable:fira_message.sim_to_ref.Replacement.robots)
  return robots_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement >*
Replacement::mutable_robots() {
  // @@protoc_insertion_point(field_mutable_list:fira_message.sim_to_ref.Replacement.robots)
  return &robots_;
}
inline const ::fira_message::sim_to_ref::RobotReplacement& Replacement::_internal_robots(int index) const {
  return robots_.Get(index);
}
inline const ::fira_message::sim_to_ref::RobotReplacement& Replacement::robots(int index) const {
  // @@protoc_insertion_point(field_get:fira_message.sim_to_ref.Replacement.robots)
  return _internal_robots(index);
}
inline ::fira_message::sim_to_ref::RobotReplacement* Replacement::_internal_add_robots() {
  return robots_.Add();
}
inline ::fira_message::sim_to_ref::RobotReplacement* Replacement::add_robots() {
  // @@protoc_insertion_point(field_add:fira_message.sim_to_ref.Replacement.robots)
  return _internal_add_robots();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fira_message::sim_to_ref::RobotReplacement >&
Replacement::robots() const {
  // @@protoc_insertion_point(field_list:fira_message.sim_to_ref.Replacement.robots)
  return robots_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sim_to_ref
}  // namespace fira_message

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_replacement_2eproto
