// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vssref_command.proto

#include "vssref_command.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace VSSRef {
namespace ref_to_team {
class VSSRef_CommandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VSSRef_Command>
      _instance;
} _VSSRef_Command_default_instance_;
}  // namespace ref_to_team
}  // namespace VSSRef
namespace protobuf_vssref_5fcommand_2eproto {
static void InitDefaultsVSSRef_Command() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::VSSRef::ref_to_team::_VSSRef_Command_default_instance_;
    new (ptr) ::VSSRef::ref_to_team::VSSRef_Command();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::VSSRef::ref_to_team::VSSRef_Command::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_VSSRef_Command =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVSSRef_Command}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_VSSRef_Command.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VSSRef::ref_to_team::VSSRef_Command, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VSSRef::ref_to_team::VSSRef_Command, foul_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VSSRef::ref_to_team::VSSRef_Command, teamcolor_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VSSRef::ref_to_team::VSSRef_Command, foulquadrant_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VSSRef::ref_to_team::VSSRef_Command, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VSSRef::ref_to_team::VSSRef_Command, gamehalf_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::VSSRef::ref_to_team::VSSRef_Command)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::VSSRef::ref_to_team::_VSSRef_Command_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "vssref_command.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024vssref_command.proto\022\022VSSRef.ref_to_te"
      "am\032\023vssref_common.proto\"\251\001\n\016VSSRef_Comma"
      "nd\022\032\n\004foul\030\001 \001(\0162\014.VSSRef.Foul\022 \n\tteamco"
      "lor\030\002 \001(\0162\r.VSSRef.Color\022&\n\014foulQuadrant"
      "\030\003 \001(\0162\020.VSSRef.Quadrant\022\021\n\ttimestamp\030\004 "
      "\001(\001\022\036\n\010gameHalf\030\005 \001(\0162\014.VSSRef.Halfb\006pro"
      "to3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 243);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "vssref_command.proto", &protobuf_RegisterTypes);
  ::protobuf_vssref_5fcommon_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_vssref_5fcommand_2eproto
namespace VSSRef {
namespace ref_to_team {

// ===================================================================

void VSSRef_Command::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VSSRef_Command::kFoulFieldNumber;
const int VSSRef_Command::kTeamcolorFieldNumber;
const int VSSRef_Command::kFoulQuadrantFieldNumber;
const int VSSRef_Command::kTimestampFieldNumber;
const int VSSRef_Command::kGameHalfFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VSSRef_Command::VSSRef_Command()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_vssref_5fcommand_2eproto::scc_info_VSSRef_Command.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:VSSRef.ref_to_team.VSSRef_Command)
}
VSSRef_Command::VSSRef_Command(const VSSRef_Command& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&foul_, &from.foul_,
    static_cast<size_t>(reinterpret_cast<char*>(&gamehalf_) -
    reinterpret_cast<char*>(&foul_)) + sizeof(gamehalf_));
  // @@protoc_insertion_point(copy_constructor:VSSRef.ref_to_team.VSSRef_Command)
}

void VSSRef_Command::SharedCtor() {
  ::memset(&foul_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&gamehalf_) -
      reinterpret_cast<char*>(&foul_)) + sizeof(gamehalf_));
}

VSSRef_Command::~VSSRef_Command() {
  // @@protoc_insertion_point(destructor:VSSRef.ref_to_team.VSSRef_Command)
  SharedDtor();
}

void VSSRef_Command::SharedDtor() {
}

void VSSRef_Command::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* VSSRef_Command::descriptor() {
  ::protobuf_vssref_5fcommand_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_vssref_5fcommand_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const VSSRef_Command& VSSRef_Command::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_vssref_5fcommand_2eproto::scc_info_VSSRef_Command.base);
  return *internal_default_instance();
}


void VSSRef_Command::Clear() {
// @@protoc_insertion_point(message_clear_start:VSSRef.ref_to_team.VSSRef_Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&foul_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&gamehalf_) -
      reinterpret_cast<char*>(&foul_)) + sizeof(gamehalf_));
  _internal_metadata_.Clear();
}

bool VSSRef_Command::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:VSSRef.ref_to_team.VSSRef_Command)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .VSSRef.Foul foul = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_foul(static_cast< ::VSSRef::Foul >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .VSSRef.Color teamcolor = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_teamcolor(static_cast< ::VSSRef::Color >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .VSSRef.Quadrant foulQuadrant = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_foulquadrant(static_cast< ::VSSRef::Quadrant >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double timestamp = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .VSSRef.Half gameHalf = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_gamehalf(static_cast< ::VSSRef::Half >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:VSSRef.ref_to_team.VSSRef_Command)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:VSSRef.ref_to_team.VSSRef_Command)
  return false;
#undef DO_
}

void VSSRef_Command::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:VSSRef.ref_to_team.VSSRef_Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .VSSRef.Foul foul = 1;
  if (this->foul() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->foul(), output);
  }

  // .VSSRef.Color teamcolor = 2;
  if (this->teamcolor() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->teamcolor(), output);
  }

  // .VSSRef.Quadrant foulQuadrant = 3;
  if (this->foulquadrant() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->foulquadrant(), output);
  }

  // double timestamp = 4;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->timestamp(), output);
  }

  // .VSSRef.Half gameHalf = 5;
  if (this->gamehalf() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->gamehalf(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:VSSRef.ref_to_team.VSSRef_Command)
}

::google::protobuf::uint8* VSSRef_Command::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:VSSRef.ref_to_team.VSSRef_Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .VSSRef.Foul foul = 1;
  if (this->foul() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->foul(), target);
  }

  // .VSSRef.Color teamcolor = 2;
  if (this->teamcolor() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->teamcolor(), target);
  }

  // .VSSRef.Quadrant foulQuadrant = 3;
  if (this->foulquadrant() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->foulquadrant(), target);
  }

  // double timestamp = 4;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->timestamp(), target);
  }

  // .VSSRef.Half gameHalf = 5;
  if (this->gamehalf() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->gamehalf(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:VSSRef.ref_to_team.VSSRef_Command)
  return target;
}

size_t VSSRef_Command::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:VSSRef.ref_to_team.VSSRef_Command)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .VSSRef.Foul foul = 1;
  if (this->foul() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->foul());
  }

  // .VSSRef.Color teamcolor = 2;
  if (this->teamcolor() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->teamcolor());
  }

  // double timestamp = 4;
  if (this->timestamp() != 0) {
    total_size += 1 + 8;
  }

  // .VSSRef.Quadrant foulQuadrant = 3;
  if (this->foulquadrant() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->foulquadrant());
  }

  // .VSSRef.Half gameHalf = 5;
  if (this->gamehalf() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->gamehalf());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VSSRef_Command::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:VSSRef.ref_to_team.VSSRef_Command)
  GOOGLE_DCHECK_NE(&from, this);
  const VSSRef_Command* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const VSSRef_Command>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:VSSRef.ref_to_team.VSSRef_Command)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:VSSRef.ref_to_team.VSSRef_Command)
    MergeFrom(*source);
  }
}

void VSSRef_Command::MergeFrom(const VSSRef_Command& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:VSSRef.ref_to_team.VSSRef_Command)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.foul() != 0) {
    set_foul(from.foul());
  }
  if (from.teamcolor() != 0) {
    set_teamcolor(from.teamcolor());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
  if (from.foulquadrant() != 0) {
    set_foulquadrant(from.foulquadrant());
  }
  if (from.gamehalf() != 0) {
    set_gamehalf(from.gamehalf());
  }
}

void VSSRef_Command::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:VSSRef.ref_to_team.VSSRef_Command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VSSRef_Command::CopyFrom(const VSSRef_Command& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:VSSRef.ref_to_team.VSSRef_Command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VSSRef_Command::IsInitialized() const {
  return true;
}

void VSSRef_Command::Swap(VSSRef_Command* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VSSRef_Command::InternalSwap(VSSRef_Command* other) {
  using std::swap;
  swap(foul_, other->foul_);
  swap(teamcolor_, other->teamcolor_);
  swap(timestamp_, other->timestamp_);
  swap(foulquadrant_, other->foulquadrant_);
  swap(gamehalf_, other->gamehalf_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata VSSRef_Command::GetMetadata() const {
  protobuf_vssref_5fcommand_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_vssref_5fcommand_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ref_to_team
}  // namespace VSSRef
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::VSSRef::ref_to_team::VSSRef_Command* Arena::CreateMaybeMessage< ::VSSRef::ref_to_team::VSSRef_Command >(Arena* arena) {
  return Arena::CreateInternal< ::VSSRef::ref_to_team::VSSRef_Command >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
